---
language: ruby
sudo: required
services:
  - docker
script:
  - bundle exec rspec spec/acceptance
bundler_args: --without system_tests
matrix:
  include:
  - rvm: default
    env: LINT=puppetcode
    dist: trusty
    bundler_args:
    script: bundle exec rake lint
  - rvm: default
    env: LINT=metadata
    dist: trusty
    bundler_args:
    script: bundle exec rake metadata_lint
  - rvm: default
    env: JOB=validate
    dist: trusty
    bundler_args:
    script: bundle exec rake validate
    - rvm: 2.5.3
    bundler_args: --without development release
    env: BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_setfile=debian8-64 CHECK=beaker
    services: docker